server:
  port: 9000
  servlet:
    context-path: /auth

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%t]) %blue(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2.server.authorization: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

spring:
  application:
    name: authorization-server
  thymeleaf:
    cache: true
  data:
    redis:
      host:
      port: 6379
      username:
      password:

  cache:
    type: redis
    redis:
      time-to-live: 60000

  rabbitmq:
    host:
    port: 5672
    username:
    password:

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

authorization:
  config:
    rabbitmq:
      key:
        widget: widget-key
        logo-update: logo.update
      queue:
        widget: widget-queue
        logo-update: logo-update-queue
      exchange:
        name: topic-exchange
    security:
      allowed-origins:
        - https://app.chatcraft.cc
        - https://factorai-370af.web.app
        - http://gateway-service:8080
      location: https://api.chatcraft.cc/auth

# External service URLs
onboarding:
  service:
    url: http://onboarding-service:8001

billing:
  service:
    url: http://billing-service:8000

chat:
  service:
    url: http://chat-service:8000